### ISSUE TITLE
[android] Hiding the statusbar does not hide the bottombar.

### ISSUE THREAD

**Issue by youzi** [vigour-io/statusbar#9]
Probably expected behaviour, but we either need an option or a plugin to hide the bottom bar.

Screenshot by sbs:
![image](https://cloud.githubusercontent.com/assets/5662898/13879770/86850b28-ed19-11e5-9c2f-54dccd735fb5.png)

**Comment by shawninder** [comment]
I think this should be a separate plugin, but it can also be part of `statusbar` as long as it's possible to hide and show these bars independantly. For our current use, hiding and showing both bars at the same time is fine, but I'm thinking that some apps may prefer to hide only one or the other.

**Comment by marcusbesjes** [comment]
I think it should be part of `statusbar` and it should allow for control over each individual aspect.

**Comment by youzi** [comment]
@julianshutt @marcusbesjes Could you align on the priority of this? It's affecting vigour-io/sbs#147

**Comment by marcusbesjes** [comment]
I aligned with @michielibiza. We will first implement a quick fix that will hide the bottom bar on statusbar hidden. ETA for that is next Thursday. This does imply a new build and new version in the store.
At the same time I will spec out the API to include specific controls for each aspect and Michiel will then implement that without the added pressure of the "live customer issue".

**Comment by shawninder** [comment]
@marcusbesjes Perhaps it's possible to do this temporary solution but allow the final desired behaviour (hiding bars separately) to be implement without needing another native build?

**Comment by marcusbesjes** [comment]
@shawninder hiding and showing the navigation bar is currently not supported on the native side so adding that will require a new native build for sure.

**Comment by shawninder** [comment]
yeah I know, what I mean is that once you have that new native build, it would be nice if you didn't need another new native build when you allow hiding bars individually in the future.

**Comment by marcusbesjes** [comment]
Yes I've added the specs to the README.md and I think we can just implement those and go for a single refactor, not hotfixing and then real fixing.

**Comment by michielibiza** [comment]
@shawninder I'm not sure i understand what you mean: if you want to change the behaviour of the plugin you need by definition a new build and a new release in the store. I'm a missing what you mean?

@marcusbesjes I've had a look and can deliver the version of the plugin that hides both bars at the same time tomorrow. _BUT_ I don't think it's feasible to make a plugin that hides them separately. The API android of android is to set combinations of flags and these combinations work subtly different on different android versions. Now it would be possible to make an app do what you want, but we are making a plugin that should implement the general case. This is too error prone.

What I would advice is:
- keep the API as it is now
- make the android plugin ignore `display: overlap` and treat it as `display: top` because overlay is buggy in a plugin setup

**Comment by shawninder** [comment]
@michielibiza I know new native behaviour means a new build. I was just hoping that the next build we make could include all the behaviour we want. If this is more complicated than I think, then forget it. The most important part is to be able to hide the bottom part soon (even if it means hiding them both at once, even if it means making a new build when/if we add the possibility of hiding them separately). You seem to understand this perfectly so just forget about what I said :)

**Comment by marcusbesjes** [comment]
@michielibiza we're actually using `display: overlay` at the moment because `display:top` "shoves" / "shifts" the interface down / up when switching to `hidden`.

About the preliminary navbar behavior: Will you let me know when can I test it?

**Comment by michielibiza** [comment]
Hey @marcusbesjes I didn't have much time yet. So I don't have a solution: keeping overlay functionality really makes it more complicated and I need a good stretch of time to see how to make it work on all android versions. 
The thing is I won't have as much time next week as I thought I would, since I will have the children with me in Holland. I'm sorry man but I really can't give much of an estimate right now.
